### PR TITLE
Delete confusing code

### PR DESCRIPTION
**Pull request by LukasTomek**
I don't know why I upload version with unnecessary code. This is reviewed version. I can't find declaration of soundSource? I don't understand why it's working, it should be global variable for functions playSound and stopSound.

### CODE REVIEW

**Comment by danielalbertjeffery** [comment]
Just to clarify, the code that you deleted wasn't necessary for it to function?

**Comment by danielalbertjeffery** [comment]
Because of the "immediately invoke function expression" (the outer function) - there are technically no 'global' variables at all. 

But I think you meant 'global' as in every part of the code being able to access them?

**Comment by danielalbertjeffery** [comment]
I re-read this part: 

'I can't find declaration of soundSource? I don't understand why it's working, it should be global variable for functions playSound and stopSound.'

I understand what you're saying now. So when you don't declare a variable, JavaScript will automatically create a variable in the global scope. 

So if you went into the console and typed in `soundSource` it would have access to that. 

There is a thing called 'strict mode' in JavaScript where if you forget the var keyword, it will not create a global variable (which most people would say is undesirable) it will give you an error instead. 

Hope that makes sense, if not feel free to ask me to clarify on Slack!

(By the way, when I was initially cleaning/refactoring the code I probably removed some variables that I thought weren't being used accidentally!)

**Comment by LukasTomek** [comment]
Yes, firstly I thought that I need to measure when track stop play, but I found out that it's enough to check If there was sound played before.
Thank you. Now it's clear.

**Pull request merged**
