### PR TITLE
fixed indentation

### PR DESCRIPTION
**Pull request by nii236**
Fixed indentation and tag ordering in the `index.html` file

### CODE REVIEW

**Comment by danielalbertjeffery** [comment]
Nice and neat Johnny ;) Two spaces for life

I made some changes, updated it to the latest version which includes the
most recent styling, animations etc.

I also uploaded the sounds instead of referencing them from CodePen's
servers. Apparently all browsers support .mp3 now...

http://caniuse.com/#feat=mp3

So I converted the files that were .wav into .mp3 for consistency.

Daniel

**Comment by nii236** [comment]
Please don't push directly into the master branch as it can (and did) break branches, including this one.

Best way to go is to push to a branch then create a pull request, get comments from everyone then merge it.

I've fixed it this time though.

**Comment by danielalbertjeffery** [comment]
Hey Johnny,

Can you please explain that in a bit more detail? What branch was broken,
and what was the effect of that?

You reverted it back to a version which doesn't represent the most up to
date version, so I don't see how that is fixing anything?

**Comment by jgunnink** [comment]
@danielalbertjeffery have a read of [this](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow)

**Comment by nii236** [comment]
Hey dude.

Generally you branch, then merge into `master` or `develop`. The target branches can't be modified otherwise you have merged conflicts.

General workflow:

photo on 25-11-2015 at 16 28

There is now, however, a new commit in the master branch. There are merge conflicts (because my branch and the master branch both modify the same line). So I can not merge anymore!

photo on 25-11-2015 at 16 28 2

I have to rebase first. This means I grab the latest commit on the master branch (containing your new commit), then play my branches commits on top of it. THEN I can merge it back in.

**Comment by danielalbertjeffery** [comment]
Hey Johnny, JK

I essentially understand the premise of what you are saying, and I agree
with the workflow, commiting to branch and then merging. We are all a bit
unaccustomed with working well with GitHub, and will need to work out a
good workflow.

The problem is that what I was pushing was intended to be the master
branch, as it represents the version that we have been working on, i.e it
is the baseline. So in that case I was happy to overwrite all of the
existing code.

When you reverted it back, you reverted it back to something that wasn't
really up to date.

I went through and looked at the code, and I could see that Lukas had added
one piece of functionality (the ability to stop a character sound before
playing another), which I wasn't aware of at the time, but even so it would
have made more sense for that change to be merged into what I pushed
recently.

It would be difficult for you to know what was the most up to date code
because you haven't been involved in making the game.

Lukas acknowledged when he uploaded the files initially that he didn't know
what was the most up to date version (as we had a few CodePen's), so he
uploaded the version that was on his computer (which had the stop
functionality).

The only change that you made as far as I can see was to indent the
index.html, so I don't think that was a particularly big thing to break -
and the files that were uploaded had the correct indentation - as well as
other changes.

The state that you referred it back to didn't have a lot of the things
which we had been working on.

If you would like to be more involved in the project that is perfectly
fine, but I think that at the least you should attend meetups so that you
are aware of what is going on and what is the latest code. Otherwise I
don't really see how you would be in a position to manage the project more
effectively than those who have been attending meetups and creating the game

**Pull request merged**
